# This file was generated by GoReleaser. DO NOT EDIT.
cask "proxydoctor" do
  version "0.4.0"

  on_macos do
    sha256 "fb3cc9aa47abf71a3f091d438df53128e4a8547fdfcbaa254c0dd77b56daaa43"
    url "https://github.com/francomano/ProxyDoctor/releases/download/v#{version}/proxydoctor_#{version}_darwin_all.tar.gz",
        verified: "github.com/francomano/ProxyDoctor/"
  end

  on_linux do
    on_intel do
      sha256 "dcd4cb4ce8d143e27cd82ccfcadc9f2ee2b4e7daf722fc6bcda1a9964326b72c"
      url "https://github.com/francomano/ProxyDoctor/releases/download/v#{version}/proxydoctor_#{version}_linux_amd64.tar.gz",
        verified: "github.com/francomano/ProxyDoctor/"
    end
    on_arm do
      sha256 "d8983732f660dfc65154a6aa59c13e6e73ba8c655f0acba51f16144424cbb345"
      url "https://github.com/francomano/ProxyDoctor/releases/download/v#{version}/proxydoctor_#{version}_linux_arm64.tar.gz",
        verified: "github.com/francomano/ProxyDoctor/"
    end
  end

  name "proxydoctor"
  desc "Comprehensive proxy diagnostics tool: test, compare and use HTTP/HTTPS/SOCKS4/SOCKS5 proxies"
  homepage "https://github.com/francomano/ProxyDoctor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proxydoctor"

  # No zap stanza required

  caveats <<~EOS
    The binary is not signed or notarized. If macOS blocks it, run:
      xattr -d com.apple.quarantine "$(brew --prefix)/bin/proxydoctor"
  EOS
end
